spring:
    r2dbc:
        url: r2dbc:h2:mem:///demo;DB_CLOSE_DELAY=-1
        username: sa
        password:
    flyway:
        url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
        user: sa
        password:
        locations: classpath:/db/migration
        enabled: true
server:
    port: 8080
logging:
    level:
        org.springframework.data.r2dbc: DEBUG
